In [31]:
import torch
torch.__version__

'2.0.1+cpu'

In [2]:
scalar = torch.tensor(1)
scalar.ndim

0

In [3]:
scalar.item()

1

In [4]:
# Vector
vec = torch.tensor([1,2])
vec

tensor([1, 2])

In [7]:
vec.ndim

1

In [8]:
vec.shape

torch.Size([2])

In [9]:
# Matrix 

MATRIX = torch.tensor([[1,2],
                       [2,3]])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX.ndim

2

In [21]:
## Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,12,4]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 5, 12,  4]]])

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR.ndim

3

In [28]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  4,  5],
        [ 5, 12,  4]])

In [29]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118
     ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
     ------ --------------------------------- 0.6/3.9 MB 13.4 MB/s eta 0:00:01
     ------------ --------------------------- 1.2/3.9 MB 12.7 MB/s eta 0:00:01
     ----------------- ---------------------- 1.7/3.9 MB 12.3 MB/s eta 0:00:01
     ---------------------- ----------------- 2.3/3.9 MB 12.0 MB/s eta 0:00:01
     ---------------------------- ----------- 2.8/3.9 MB 11.9 MB/s eta 0:00:01
     ---------------------------------- ----- 3.3/3.9 MB 11.8 MB/s eta 0:00:01
     ---------------------------------------  3.9/3.9 MB 11.9 MB/s eta 0:00:01
     ---------------------------------------  3.9/3.9 MB 11.9 MB/s eta 0:00:01
     ---------------------------------------  3.9/3.9 MB 11.9 MB/s eta 0:00:01
     ---------------------------------------  3.9/3.9 MB 11.9 MB/s eta 0:00:01
     ---------------------------------------  3.9/3.9 MB 11.9 MB/s eta 0:00:01
 

In [32]:
torch.cuda.is_available()

False

In [48]:
# Random Tensors

rand = torch.rand(3,4)
rand

tensor([[0.4867, 0.8912, 0.5263, 0.7068],
        [0.4328, 0.6448, 0.9781, 0.4908],
        [0.5918, 0.3256, 0.9921, 0.5435]])

In [49]:
# random image tensor

random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor

tensor([[[4.4662e-01, 9.2516e-01, 2.7449e-01],
         [1.6001e-01, 5.4482e-01, 3.0038e-01],
         [1.3288e-01, 8.1928e-01, 3.3540e-01],
         ...,
         [1.4517e-01, 5.6379e-01, 7.9808e-01],
         [4.3415e-01, 4.2767e-01, 4.6685e-01],
         [5.0673e-02, 9.1625e-01, 9.5731e-01]],

        [[6.2637e-02, 3.4098e-01, 6.9699e-02],
         [1.5517e-01, 3.4872e-01, 2.6324e-01],
         [5.0088e-01, 2.2099e-01, 8.2395e-01],
         ...,
         [1.6801e-01, 4.6348e-01, 1.7265e-01],
         [6.4591e-01, 8.4764e-04, 2.6885e-01],
         [1.6810e-01, 4.6325e-01, 8.0876e-01]],

        [[1.4404e-01, 4.8215e-01, 2.6361e-02],
         [5.0089e-01, 7.1365e-01, 5.6500e-01],
         [7.2154e-01, 1.4287e-02, 3.9427e-02],
         ...,
         [1.7693e-01, 1.1669e-01, 1.5447e-01],
         [9.5941e-01, 7.9509e-01, 3.7176e-01],
         [8.0689e-01, 5.4832e-01, 1.7649e-01]],

        ...,

        [[1.0974e-01, 5.3565e-01, 5.2879e-01],
         [9.5291e-01, 4.3501e-01, 8.2691e-01]

In [50]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [51]:
random_image_tensor.ndim

3

In [52]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
rand*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
torch.arange(1,12,1.5,dtype=torch.float16)

tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000, 11.5000],
       dtype=torch.float16)

In [71]:
torch.tensor([1,2,3,4,5],
             dtype=None,
             device='cpu', 
             requires_grad=False)

tensor([1, 2, 3, 4, 5])

In [72]:
# Expected one of cpu,
# cuda, ipu, xpu, mkldnn,
# opengl, opencl, ideep, hip, ve
# , fpga, ort, xla, lazy, vulkan,
# mps, meta, hpu, mtia, privateuseone
# device type at start of device string: d


In [74]:
x, y = 252 * pow(10,-6), 1.95 * pow(10,-3)
x,y

(0.000252, 0.00195)

In [75]:
y/x

7.738095238095238